### ISSUE TITLE
Remove extra stuff

### ISSUE THREAD

**Issue by austingulati** [drood1/ACG_Melting_Project#8]
This might be a good idea since the repository is open source. We can't delete the history but it might be good to get rid of the homework stuff like subdivision and simplification

**Comment by karl-olsen** [comment]
Just a heads up, I probably won't have any visible work done tonight.
Basically my computer is really weird and can't run GLFW so I've been
having to use GLUT all semester. I'm gonna be spending tonight working on
setting up the code to be able to work on both of our computers with
minimal effort/changes required. I'll probably meet Barb after class
tomorrow as well for help with this.

**Comment by austingulati** [comment]
No problem. I think we have enough for the first progress post. If you want
to work on any of the non-coding stuff you can include that on your
progress post. I'm pretty sure we both have to make one
